--------------------------------------------------------
--  Arquivo criado - segunda-feira-fevereiro-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "C##DEVELOPER"."CLIENTES" 
   (	"IDCLI" NUMBER(*,0), 
	"TIPO_PESSOA" VARCHAR2(15 BYTE), 
	"CPF" VARCHAR2(20 BYTE), 
	"NOME" VARCHAR2(50 BYTE), 
	"TELEFONE" VARCHAR2(11 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DATA_CRIADO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##DEVELOPER.CLIENTES
SET DEFINE OFF;
Insert into C##DEVELOPER.CLIENTES (IDCLI,TIPO_PESSOA,CPF,NOME,TELEFONE,EMAIL,DATA_CRIADO) values ('6','PF','888888888','Jhoanvic','98989898','jps@gmail.com',to_date('13/02/22','DD/MM/RR'));
Insert into C##DEVELOPER.CLIENTES (IDCLI,TIPO_PESSOA,CPF,NOME,TELEFONE,EMAIL,DATA_CRIADO) values ('4','PF','60708009044','Joao Pedro','98990102033','jp@gmail.com',to_date('13/02/22','DD/MM/RR'));
Insert into C##DEVELOPER.CLIENTES (IDCLI,TIPO_PESSOA,CPF,NOME,TELEFONE,EMAIL,DATA_CRIADO) values ('5','PJ','60708009044','Alessandro Martins','988961126','alehmartinns@gmail.com',to_date('13/02/22','DD/MM/RR'));
Insert into C##DEVELOPER.CLIENTES (IDCLI,TIPO_PESSOA,CPF,NOME,TELEFONE,EMAIL,DATA_CRIADO) values ('8','PF','123','teste','123','teste@teste',to_date('13/02/22','DD/MM/RR'));
Insert into C##DEVELOPER.CLIENTES (IDCLI,TIPO_PESSOA,CPF,NOME,TELEFONE,EMAIL,DATA_CRIADO) values ('9','PJ','60708009044','Joao Pedro Sales','98989898','jps@gmail.com',to_date('13/02/22','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DEVELOPER"."CLIENTES_PK" ON "C##DEVELOPER"."CLIENTES" ("IDCLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "C##DEVELOPER"."CLIENTES" MODIFY ("IDCLI" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CLIENTES" MODIFY ("CPF" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CLIENTES" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CLIENTES" MODIFY ("DATA_CRIADO" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("IDCLI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
