--------------------------------------------------------
--  Arquivo criado - segunda-feira-fevereiro-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTAS
--------------------------------------------------------

  CREATE TABLE "C##DEVELOPER"."CONTAS" 
   (	"IDCON" NUMBER(*,0), 
	"IDCLI" NUMBER(*,0), 
	"MOV_CREDITO" FLOAT(126), 
	"MOV_DEBITO" FLOAT(126), 
	"SALDO_INICIAL" FLOAT(126), 
	"SALDO_FINAL" FLOAT(126), 
	"DATA_CRIADO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##DEVELOPER.CONTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CONTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DEVELOPER"."CONTAS_PK" ON "C##DEVELOPER"."CONTAS" ("IDCON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONTAS
--------------------------------------------------------

  ALTER TABLE "C##DEVELOPER"."CONTAS" MODIFY ("IDCON" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CONTAS" MODIFY ("IDCLI" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CONTAS" MODIFY ("SALDO_INICIAL" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CONTAS" MODIFY ("DATA_CRIADO" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."CONTAS" ADD CONSTRAINT "CONTAS_PK" PRIMARY KEY ("IDCON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTAS
--------------------------------------------------------

  ALTER TABLE "C##DEVELOPER"."CONTAS" ADD CONSTRAINT "CONTA_CLIENTE_FK" FOREIGN KEY ("IDCLI")
	  REFERENCES "C##DEVELOPER"."CLIENTES" ("IDCLI") ENABLE;
