--------------------------------------------------------
--  Arquivo criado - segunda-feira-fevereiro-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ENDERECOS
--------------------------------------------------------

  CREATE TABLE "C##DEVELOPER"."ENDERECOS" 
   (	"IDEND" NUMBER(*,0), 
	"IDCLI" NUMBER(*,0), 
	"RUA" VARCHAR2(50 BYTE), 
	"NUMERO" NUMBER(*,0), 
	"COMPLEMENTO" VARCHAR2(50 BYTE), 
	"BAIRRO" VARCHAR2(50 BYTE), 
	"CIDADE" VARCHAR2(50 BYTE), 
	"UF" VARCHAR2(10 BYTE), 
	"CEP" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##DEVELOPER.ENDERECOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ENDERECO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##DEVELOPER"."ENDERECO_PK" ON "C##DEVELOPER"."ENDERECOS" ("IDEND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ENDERECOS
--------------------------------------------------------

  ALTER TABLE "C##DEVELOPER"."ENDERECOS" MODIFY ("IDEND" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."ENDERECOS" MODIFY ("IDCLI" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."ENDERECOS" MODIFY ("RUA" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."ENDERECOS" MODIFY ("BAIRRO" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."ENDERECOS" MODIFY ("CIDADE" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."ENDERECOS" MODIFY ("UF" NOT NULL ENABLE);
  ALTER TABLE "C##DEVELOPER"."ENDERECOS" ADD CONSTRAINT "ENDERECO_PK" PRIMARY KEY ("IDEND")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENDERECOS
--------------------------------------------------------

  ALTER TABLE "C##DEVELOPER"."ENDERECOS" ADD CONSTRAINT "CLIENTE_FK" FOREIGN KEY ("IDCLI")
	  REFERENCES "C##DEVELOPER"."CLIENTES" ("IDCLI") ON DELETE CASCADE ENABLE;
